name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Ganti jika branch utama Anda bukan 'main'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Pastikan ini versi Flutter Anda
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter Web with Correct Base HREF
        run: |
          # Pastikan Flutter Web diaktifkan untuk build
          flutter config --enable-web

          # Bangun aplikasi web dengan base-href yang benar
          # /${{ github.event.repo.name }}/ akan menjadi /flutter_pbp/
          # Pastikan web-renderer html digunakan untuk konsistensi dan kompatibilitas
          flutter build web --release --base-href /${{ github.event.repo.name }}/ --web-renderer html

      - name: Verify Base HREF in index.html (Debug Step) # BARU: Untuk verifikasi
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of build/web directory:"
          ls -R build/web
          echo "Content of index.html after build:"
          cat build/web/index.html | grep '<base href'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # HAPUS BARIS INI: base_url: /${{ github.event.repo.name }}/
          # Kita akan mengandalkan base-href yang sudah benar dari build Flutter
          # dan `peaceiris` tidak boleh mengubahnya jika sudah benar.
          # CNAME: your-custom-domain.com