name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

# DITAMBAHKAN: Memberikan izin kepada Actions untuk menulis ke repo Anda
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        # Pastikan REPO-NAME ini sudah benar
        run: flutter build web --release --base-href="/flutter_pbp/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web