name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Ganti jika branch utama Anda bukan 'main'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Pastikan ini versi Flutter Anda
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: |
          # Penting: Pastikan base-href ini sesuai dengan path GitHub Pages Anda
          # /${{ github.event.repo.name }}/ akan menjadi /flutter_pbp/
          flutter build web --release --base-href /${{ github.event.repo.name }}/ --web-renderer html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # DIUBAH: Gunakan v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # BARU: Secara eksplisit tentukan base_url untuk Pages
          # Ini akan memastikan tag <base> di index.html benar-benar diupdate oleh action deploy
          base_url: /${{ github.event.repo.name }}/ # BARU
          # CNAME: your-custom-domain.com # Hapus atau komen baris ini jika tidak menggunakan custom domain